### ISSUE TITLE
Fix docu Swagger-Documentation

### ISSUE THREAD

**Issue by jolo-dev** [n1ghty1993/Coronahelfer-Hackathon#20]
Please, change the field `userName` to `email` to avoid confusion.

![screenshot-dev coronahelfer eu-2020 04 04-18_15_36](https://user-images.githubusercontent.com/54506108/78455743-620bb200-76a0-11ea-9d4b-d4809cc11659.png)

**Comment by JanneckLange** [comment]
The swagger documentation is outdated and will be removed soon. We have a different concept in mind.
